version: "3"

services:
  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: Arnold
    #   MONGO_INITDB_ROOT_PASSWORD: contrasena123
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: Arnold
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: contrasena123

  # backend:
  # image: golang
